# Generated by Django 3.2.7 on 2022-01-19 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('math_marks', models.IntegerField(verbose_name='Maths Marks')),
                ('phy_marks', models.IntegerField(verbose_name='Physics Marks')),
                ('chem_marks', models.IntegerField(verbose_name='Chemistry Marks')),
                ('bio_marks', models.IntegerField(verbose_name='Biology Marks')),
                ('comp_marks', models.IntegerField(verbose_name='Computer Marks')),
                ('eng_marks', models.IntegerField(verbose_name='English Marks')),
                ('hindi_marks', models.IntegerField(verbose_name='Hindi Marks')),
                ('sans_marks', models.IntegerField(verbose_name='Sanskrit Marks')),
                ('phe_marks', models.IntegerField(verbose_name='Physical Education Marks')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Exam Name')),
                ('session', models.CharField(max_length=10, verbose_name='Exam Session')),
                ('cls', models.IntegerField(verbose_name='Exam of Class')),
                ('marks', models.ManyToManyField(to='exam.Marks')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.teacher')),
            ],
        ),
    ]
