# Generated by Django 3.2.7 on 2022-01-20 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='marks',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='bio_marks',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='chem_marks',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='comp_marks',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='eng_marks',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='hindi_marks',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='math_marks',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='phe_marks',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='phy_marks',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='sans_marks',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='student',
        ),
        migrations.AddField(
            model_name='marks',
            name='marks_mx',
            field=models.IntegerField(default=1, verbose_name='Maximum Marks'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marks',
            name='marks_ob',
            field=models.IntegerField(default=1, verbose_name='Marks Obtained'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marks',
            name='subject',
            field=models.CharField(choices=[('MATH', 'Mathematics'), ('PHY', 'Physics'), ('CHEM', 'Chemistry'), ('BIO', 'Biology'), ('CS', 'Computer Science'), ('ENG', 'English'), ('HIN', 'Hindi'), ('SANS', 'Sanskrit'), ('PHE', 'Physical Education')], default=1, max_length=20, verbose_name='Subject'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
        migrations.AddField(
            model_name='marks',
            name='result',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam.result'),
        ),
    ]
