# Generated by Django 4.0.1 on 2022-03-15 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_remove_exam_name_exam_exam_name_alter_exam_cls_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='marks_mx',
            field=models.IntegerField(blank=True, help_text='Maximum marks in the subject', null=True, verbose_name='Maximum Marks'),
        ),
        migrations.AlterField(
            model_name='marks',
            name='marks_ob',
            field=models.IntegerField(blank=True, help_text='Marks obtained in the subject', null=True, verbose_name='Marks Obtained'),
        ),
    ]
