# Generated by Django 4.0.1 on 2022-05-22 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_alter_exam_cls_alter_subject_subject_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='edited_by_class_teacher',
            field=models.BooleanField(default=False, editable=False, verbose_name='Edited by Class Teacher'),
        ),
    ]
