# Generated by Django 4.0.1 on 2022-05-28 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam', '0009_exam_edited_by_class_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=30, verbose_name="Exam Admin's Name")),
                ('user_name', models.CharField(help_text='Enter an username that you will use for logging in.', max_length=150, unique=True, verbose_name='User Name')),
                ('user', models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
