# Generated by Django 4.0.1 on 2022-05-30 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('exam', '0010_examadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='cls',
            field=models.ForeignKey(help_text='The class of which the exam is held. This will be pre-filled with your class if you are a class teacher.', on_delete=django.db.models.deletion.CASCADE, to='core.class', verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='marks',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject', verbose_name='Subject'),
        ),
        migrations.DeleteModel(
            name='ExamAdmin',
        ),
    ]
