# Generated by Django 4.0.1 on 2022-06-01 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_teacher_teacher_of_class'),
        ('exam', '0012_delete_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='cls',
            field=models.ForeignKey(help_text='The class of which the exam is held. This will be pre-filled with your class if you are a class teacher.', on_delete=django.db.models.deletion.PROTECT, to='core.class', verbose_name='Class'),
        ),
    ]
