# Generated by Django 4.0.1 on 2022-06-28 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0013_alter_exam_cls'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=50, verbose_name='Exam Name')),
                ('exam_code', models.CharField(max_length=10, verbose_name='Exam Code')),
            ],
        ),
        migrations.RemoveField(
            model_name='exam',
            name='exam_name',
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_type',
            field=models.ForeignKey(default=0, help_text='Select the type of exam from the dropdown.', on_delete=django.db.models.deletion.RESTRICT, to='exam.examtype', verbose_name='Exam Type'),
            preserve_default=False,
        ),
    ]
