# Generated by Django 4.0.1 on 2022-01-30 06:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_name',
        ),
        migrations.AddField(
            model_name='student',
            name='admission_category',
            field=models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V')], max_length=3, null=True, verbose_name='Admission Category'),
        ),
        migrations.AddField(
            model_name='student',
            name='fathers_name',
            field=models.CharField(max_length=30, null=True, verbose_name="Father's Name"),
        ),
        migrations.AddField(
            model_name='student',
            name='mothers_name',
            field=models.CharField(max_length=30, null=True, verbose_name="Mother's Name"),
        ),
        migrations.AddField(
            model_name='student',
            name='school_code',
            field=models.IntegerField(null=True, verbose_name='School Code'),
        ),
        migrations.AddField(
            model_name='student',
            name='social_category',
            field=models.CharField(choices=[('GEN', 'GEN'), ('SC', 'SC'), ('ST', 'ST'), ('OBC', 'OBC')], max_length=3, null=True, verbose_name='Social Category'),
        ),
        migrations.AddField(
            model_name='student',
            name='student_name',
            field=models.CharField(max_length=30, null=True, verbose_name="Student's Name"),
        ),
        migrations.AlterField(
            model_name='student',
            name='aadhar_number',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('^\\d{12}$', 'Aadhar should be of 12 digits')], verbose_name='Aadhar Number'),
        ),
        migrations.AlterField(
            model_name='student',
            name='uid',
            field=models.CharField(max_length=16, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^\\d{15,16}$', 'UID should be of 15 digits')], verbose_name="Student's UID Number"),
        ),
    ]
