# Generated by Django 4.0.1 on 2022-01-30 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_student_first_name_remove_student_full_name_and_more'),
    ]

    operations = [
    ]
