# Generated by Django 4.0.1 on 2022-01-30 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20220130_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='admission_category',
            field=models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V')], max_length=3, verbose_name='Admission Category'),
        ),
        migrations.AlterField(
            model_name='student',
            name='fathers_name',
            field=models.CharField(max_length=30, verbose_name="Father's Name"),
        ),
        migrations.AlterField(
            model_name='student',
            name='school_code',
            field=models.IntegerField(verbose_name='School Code'),
        ),
        migrations.AlterField(
            model_name='student',
            name='social_category',
            field=models.CharField(choices=[('GEN', 'GEN'), ('SC', 'SC'), ('ST', 'ST'), ('OBC', 'OBC')], max_length=3, verbose_name='Social Category'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_name',
            field=models.CharField(max_length=30, verbose_name="Student's Name"),
        ),
    ]
