# Generated by Django 4.0.1 on 2022-01-30 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_student_admission_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mothers_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name="Mother's Name"),
        ),
    ]
