# Generated by Django 4.0.1 on 2022-01-30 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_alter_student_aadhar_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='cls',
            field=models.IntegerField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V'), ('VI', 'VI'), ('VII', 'VII'), ('VIII', 'VIII'), ('IX', 'IX'), ('X', 'X'), ('XI', 'XI'), ('XII', 'XII')], verbose_name='Class'),
        ),
    ]
