# Generated by Django 4.0.1 on 2022-02-01 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0009_alter_student_cls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='last_name',
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_name',
            field=models.CharField(default='Tecaher', max_length=30, verbose_name="Teacher's Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(default=None, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='user_name',
            field=models.CharField(default='Tecaher', help_text='Enter an username that you will use for loging in.', max_length=30, verbose_name='User Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.CharField(blank=True, choices=[('MATH', 'Mathematics'), ('PHY', 'Physics'), ('CHEM', 'Chemistry'), ('BIO', 'Biology'), ('CS', 'Computer Science'), ('ENG', 'English'), ('HIN', 'Hindi'), ('SANS', 'Sanskrit'), ('PHE', 'Physical Education')], max_length=20, null=True, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_of_class',
            field=models.CharField(blank=True, choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V'), ('VI', 'VI'), ('VII', 'VII'), ('VIII', 'VIII'), ('IX', 'IX'), ('X', 'X'), ('XI', 'XI'), ('XII', 'XII')], max_length=4, null=True, verbose_name='Class Tecaher Of'),
        ),
    ]
