# Generated by Django 4.0.1 on 2022-03-12 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_remove_teacher_first_name_remove_teacher_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='social_category',
            field=models.CharField(choices=[('GEN', 'General'), ('SC', 'SC'), ('ST', 'ST'), ('OBC', 'OBC')], max_length=7, verbose_name='Social Category'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user_name',
            field=models.CharField(help_text='Enter an username that you will use for loging in.', max_length=150, verbose_name='User Name'),
        ),
    ]
