# Generated by Django 4.0.1 on 2022-03-19 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_subject_remove_marks_marks_mx_alter_marks_subject'),
        ('students', '0012_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='cls_subjects',
        ),
        migrations.AddField(
            model_name='class',
            name='cls_subjects',
            field=models.ManyToManyField(to='exam.Subject', verbose_name='Subjects of the Class'),
        ),
        migrations.AlterField(
            model_name='student',
            name='cls',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.class', verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_teachers', to='exam.subject', verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_of_class',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_teacher', to='students.class', verbose_name='Class Teacher Of'),
        ),
    ]
