# Generated by Django 4.0.1 on 2022-03-19 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_remove_class_cls_subjects_class_cls_subjects_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name': 'Class', 'verbose_name_plural': 'Classes'},
        ),
    ]
