# Generated by Django 4.0.1 on 2022-04-05 12:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_alter_exam_cls_alter_subject_subject_name'),
        ('students', '0014_alter_class_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='doa',
        ),
        migrations.AddField(
            model_name='class',
            name='section',
            field=models.CharField(blank=True, help_text='Section name like A, B, C, ...', max_length=1, null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='class',
            name='stream',
            field=models.CharField(blank=True, help_text="Stream of the Class if class > XI", max_length=10, null=True, verbose_name="Stream")
        ),
        migrations.AddField(
            model_name='student',
            name='admission_flag',
            field=models.CharField(choices=[('Exsiting', 'Existing')], default='', max_length=8, verbose_name='Admission Flag'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='admission_number',
            field=models.CharField(default='', max_length=6, validators=[django.core.validators.RegexValidator('^\\d{6}$', 'Admission Year should be format XXXXXXX')], verbose_name='Admission Number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='admission_year',
            field=models.CharField(default='', max_length=4, validators=[django.core.validators.RegexValidator('^\\d{4}$', 'Admission Year should be format YYYY')], verbose_name='Admission Year'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3, null=True, verbose_name='Blood Group'),
        ),
        migrations.AddField(
            model_name='student',
            name='bpl',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='', max_length=3, verbose_name='BPL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email ID'),
        ),
        migrations.AddField(
            model_name='student',
            name='extra_subjects_opted',
            field=models.ManyToManyField(to='exam.Subject', verbose_name='Extra Subjects Opted (if any)'),
        ),
        migrations.AddField(
            model_name='student',
            name='kvs_ward',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='', max_length=3, verbose_name='KVS Ward'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='minority',
            field=models.CharField(choices=[('NA', 'Not Applicable'), ('Muslim', 'Muslim')], default='', max_length=6, verbose_name='Minority'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='physically_disabled',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='', max_length=3, verbose_name='Physically Disabled'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='rte',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='', max_length=3, verbose_name='RTE'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='sibbling',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='', max_length=3, verbose_name='Sibbling'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='single_girl_child',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='', max_length=3, verbose_name='Single Girl Child'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='student_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Deactive', 'Deactive')], default='', max_length=8, verbose_name='Student Status'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='tc_issued',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='', max_length=3, verbose_name='TC Issued'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='mothers_name',
            field=models.CharField(default='', max_length=30, verbose_name="Mother's Name"),
            preserve_default=False,
        ),
    ]
