# Generated by Django 4.0.1 on 2022-05-13 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_remove_student_doa_class_section_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='extra_subjects_opted',
            new_name='optional_subjects_opted',
        ),
        migrations.AlterField(
            model_name='student',
            name='admission_flag',
            field=models.CharField(choices=[('Existing', 'Existing')], max_length=8, verbose_name='Admission Flag'),
        ),
    ]
