# Generated by Django 4.0.1 on 2022-05-21 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0016_rename_extra_subjects_opted_student_optional_subjects_opted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='doj',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user_name',
            field=models.CharField(help_text='Enter an username that you will use for logging in.', max_length=150, unique=True, verbose_name='User Name'),
        ),
    ]
