# Generated by Django 4.0.1 on 2022-05-30 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('exam', '0011_alter_exam_cls_alter_marks_subject_delete_examadmin'),
        ('students', '0017_remove_teacher_dob_remove_teacher_doj_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='teacher_of_class',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='user',
        ),
        migrations.AlterField(
            model_name='student',
            name='cls',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.class', verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='student',
            name='optional_subjects_opted',
            field=models.ManyToManyField(to='core.Subject', verbose_name='Extra Subjects Opted (if any)'),
        ),
        migrations.DeleteModel(
            name='Class',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
