# Generated by Django 4.0.1 on 2022-06-28 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_school_class_school_examadmin_school_teacher_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examadmin',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='subject_teachers', to='core.subject', verbose_name='Subject'),
        ),
    ]
