# Generated by Django 4.0.1 on 2022-08-11 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_examadmin_school_alter_teacher_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectExtras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20, verbose_name='Tag/Name')),
                ('weightage', models.FloatField(verbose_name='Weightage')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject', verbose_name='Subject')),
            ],
            options={
                'verbose_name': 'Subject Extras',
                'verbose_name_plural': 'Subject Extras',
            },
        ),
    ]
