ADMISSION_CATEGORIES = (("I","I"),("II","II"),("III","III"),("IV","IV"),("V","V"))
SOCIAL_CATEGORIES = (("GEN","General"),("SC","SC"),("ST","ST"),("OBC","OBC"))
GENDERS = (("Boy","Boy"),("Girl","Girl"))
BLOOD_GROUPS = (("A+","A+"),("A-","A-"),("B+","B+"),("B-","B-"),("O+","O+"),("O-","O-"),("AB+","AB+"),("AB-","AB-"))
STUDENT_STATUSES = (("Active","Active"),("Deactive","Deactive"))
YES_NO_CHOICES = (("YES","YES"),("NO","NO"))
MINORITIES = (("NA","Not Applicable"),("Muslim","Muslim"))
ADMISSION_FLAGS = (("Existing","Existing"),)